name: Pelican build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - run: "pip install -r requirements.txt"
      
      - run: "pelican -s publishconf.py"

      - uses: actions/upload-pages-artifact
        with:
          path: "output"
